Completed Stage 1
vdmppv-xbsoftware/webix-jet-app pull request #1
Opened 2022-04-22 20:22 UTC by vdmppv-xbsoftware

2022-04-25 11:52 UTC, fireFireee commented on sources/views/contactsInfo.js
> +					<span class='webix_icon mdi mdi-email'></span><span>${obj.Email || "Unknown"}</span> <br><br>
может лучше не показывать информацию, которой нет?
зачем нам видеть иконку со скайпом и надпись "Unknown", если у контакта он не указан?

2022-04-25 12:52 UTC, kullias commented
![Selection_999(822)](https://user-images.githubusercontent.com/31205423/165092594-788d5b9b-b380-454a-9d9e-3c33fda2efd3.png)
падает после сохранения, поменяла тип просто и нажала Save
форма не закрывается уже, только если Cancel и Discard

2022-04-25 13:04 UTC, kullias commented
даты не в том формате иногда отправляются (например по чекбоксу) и в итоге на бэкенде зануляются
![Selection_999(823)](https://user-images.githubusercontent.com/31205423/165094790-6fbb710f-1465-4fac-89c8-2f810d4fd849.png)
![Selection_999(825)](https://user-images.githubusercontent.com/31205423/165094801-58da48b4-d9e2-4352-bc20-bc353de70484.png)
![Selection_999(824)](https://user-images.githubusercontent.com/31205423/165094817-556a2160-2e36-4225-8641-6aeff9887b94.png)

2022-04-25 13:45 UTC, kullias requested changes

2022-04-25 13:45 UTC, kullias commented on sources/views/contactsInfo.js
> +					const contactItem = contactsCollection.getItem(contactId);
на моей базе детали и фотки не меняются иногда (у меня есть пустые поля и фотки кое-где не заданы)
![Peek 2022-04-25 15-44](https://user-images.githubusercontent.com/31205423/165091686-2eb7daca-ee40-4ef2-81d7-3df9f0a37fa5.gif)

2022-04-25 13:45 UTC, kullias commented on sources/views/activitiesView.js
> +	}
если пофильтровать таблицу, потом добавить новую запись (или удалить, или изменить), фильтр будет в прежнем состоянии, а фильтрация данных сбросится
надо перезапускать фильтрацию после операций add, update, delete

2022-04-25 13:45 UTC, kullias commented on sources/views/activitiesView.js
> +					header: ["Due date", {content: "datepickerFilter"}],
вероятно придется тут добавить compare чтоб показывал и те даты, где время ненулевое

2022-04-25 13:45 UTC, kullias commented on sources/views/popupEditor.js
> +									webix.confirm({
показывать эту штуку если в форме ничего юзер не поменял не надо

2022-04-25 13:45 UTC, kullias commented on sources/views/popupEditor.js
> +					TypeID: webix.rules.isNotEmpty,
когда есть required пустые поля уже не пройдут, так что можно не добавлять

2022-04-25 13:45 UTC, kullias commented on sources/views/popupEditor.js
> +								invalidMessage: "Date selection is required"
для дат и времени есть invalid message, но нету валидации

2022-04-26 10:39 UTC, kullias commented on sources/views/popupEditor.js
> +								click: () => this.closeForm()
можно было проверить на dirty,а не совсем уж убирать. хороший конфирм был же)

2022-04-26 10:48 UTC, vdmppv-xbsoftware commented on sources/views/popupEditor.js
> +								click: () => this.closeForm()
А, видимо не так понял, хорошо)

2022-04-26 11:18 UTC, kullias approved these changes

2022-04-26 11:25 UTC, fireFireee approved these changes

2022-04-26 11:25 UTC, merged